### ISSUE TITLE
Generated code has a non-deterministic order, which can impact remote cacheability when using Gradle build cache

### ISSUE THREAD

**Issue by autonomousapps** [square/AssistedInject#102]
This issue will be visible when using Gradle's remote build cache. The following screenshots are from Android Studio and a Gradle Enterprise instance used by a team at Comcast, with whom I work (I am a Gradle employee).

The tl;dr is that, given a set of inputs, this annotation processor seems to generate code with non-deterministic output (the order of methods in the generated code is what is non-deterministic). It's a classic indication of HashMap usage (or similar).

File diff (CI vs local dev build):
<img width="1792" alt="assistedinject-diff" src="https://user-images.githubusercontent.com/5402301/62418273-3a98ad00-b61a-11e9-8ca5-bf160bd7611b.png">

Gradle Enterprise task inputs comparison showing the file input that was "different" and, 
therefore, an issue for the remote build cache:
<img width="1112" alt="different-inputs" src="https://user-images.githubusercontent.com/5402301/62418270-2b196400-b61a-11e9-94d3-56639fbbd499.png">

Gradle Enterprise infrastructure comparison showing the different JDKs in use:
<img width="1054" alt="different-jdk" src="https://user-images.githubusercontent.com/5402301/62418290-6f0c6900-b61a-11e9-9620-cafc862bb76e.png">

As I said, this is a classic sign of using something like a HashMap as the data structure, because of course it has no defined order, and so different JDKs will have different implementations.

**Observation**
Generated code has non-deterministic order with respect to JDK in use

**Expectation**
Generated source code is reproducible no matter where it is generated.

**Comment by JakeWharton** [comment]
The processor is written in Kotlin so it uses `LinkedHashMap` by default, but I _always_ would use `LinkedHashMap` anyway: https://publicobject.com/2016/02/08/linkedhashmap-is-always-better-than-hashmap/

I suspect the problem is more that the differences in javac implementations or even the backing filesystems (or both) are providing the elements in different orders and we need to switch to an explicitly sorted collection rather than implicitly relying on javac for it.

**Comment by JakeWharton** [comment]
PR welcome, otherwise I'll do it on Monday or Tuesday. There's a release going out next week for incremental support so this'll be a nice tag-along.

**Comment by autonomousapps** [comment]
I see your PR fixing this (speculatively). Thank you! I did take a brief look over the weekend, but didn't have time to figure out where to place that magic line of code... :)

**Comment by JakeWharton** [comment]
I added a test which reproduced the behavior so it's (thankfully) no longer speculative.

**Comment by JakeWharton** [comment]
Released as 0.5.0.
