### ISSUE TITLE
Nested AssistedModule compilation fails with missing include error

### ISSUE THREAD

**Issue by trevjonez** [square/AssistedInject#108]
Given the following module:
```java
class Outer {
  @AssistedModule
  @Module(includes = AssistedInject_TestModule.class)
  public abstract class TestModule {}
}
```

Compilation fails with:
```
error: @AssistedModule's @Module must include AssistedInject_TestModule
```

I am not certain if nested module not being allowed is intentional or not but it seems it should either be allowed or have a specific error as output.

I have a failing unit test and will open a PR with that once I have this issue link.

**Comment by JakeWharton** [comment]
Released as 0.5.0.
