### ISSUE TITLE
InflationInject errs if parameters don't have the expected name?

### ISSUE THREAD

**Issue by oldergod** [square/AssistedInject#118]
```
    Found:
      [android.content.Context context, android.util.AttributeSet attributeSet]
    Expected:
      [android.content.Context context, android.util.AttributeSet attrs]
```
Is it a bug?

**Comment by JakeWharton** [comment]
Names used to not matter but then people complained that you had to use qualifier annotations to disambiguate multiple assisted parameters so the library was switched to use names. As a side-effect, names now matter even when there's only one parameter of a certain type.

#81 tracks the feature of not caring about names when there is only a single assisted parameter for each type.

**Comment by oldergod** [comment]
Gotta give it up for democracy
