### ISSUE TITLE
Processor claiming arguments not matching when they do in code

### ISSUE THREAD

**Issue by davidliu** [square/AssistedInject#120]
Getting this error the first time I compile each time:

```
e: error: Factory method parameters do not match constructor @Assisted parameters.
  Missing:
   * androidx.lifecycle.SavedStateHandle handle
  Unknown:
   * androidx.lifecycle.SavedStateHandle arg0
```

The argument name does actually match, and this error goes away upon building a second time. Not sure interaction is causing this.

**Comment by JakeWharton** [comment]
Dupe of #81.

**Comment by TheReprator** [comment]
I am also getting the same issue in a multi-module project,

Factory method parameters do not match constructor @Assisted parameters. Both parameter type and name must match.
    public UserAdminViewModal(@org.jetbrains.annotations.NotNull()
           ^
  Declared by constructor, unmatched in factory method:
   * androidx.lifecycle.SavedStateHandle savedStateHandle
  Declared by factory method, unmatched in constructor:
   * androidx.lifecycle.SavedStateHandle arg0

**Comment by sunnykraditya** [comment]
@TheReprator how you managed to solve it? Having the same issue in a multi-module project.

**Comment by TheReprator** [comment]
@sunnykraditya now, i don't remember the issue, anymore

**Comment by sunnykraditya** [comment]
For future solution seekers -> https://github.com/square/AssistedInject/issues/81#issuecomment-606101211
