### ISSUE TITLE
AssistedInject should take source version into consideration for Generated annotation

### ISSUE THREAD

**Issue by gavra0** [square/AssistedInject#124]
AssistedInject searches classpath for `@Generated` type https://github.com/square/AssistedInject/blob/cf2b4cf76f5769e880966bf215c00eb66c7c9259/assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/internal/generatedAnnotation.kt#L29 but it does not take source version into account. This causes issues when both annotations are present in the classpath (e.g. running with JDK11 and having `javax.annotation:javax.annotation-api:1.3.2` in the compile classpath).

Doing the same check as auto-common seems like a good solution: https://github.com/google/auto/blob/79c9d15c14a898e1ae2085f265a5396b190d7017/common/src/main/java/com/google/auto/common/GeneratedAnnotations.java#L54

**Comment by JakeWharton** [comment]
If both are present, why does that cause a problem? I assumed that any JDK 9 or newer running with source 9+ or release 9+ (or no flags) would cause the 'processing' one to be available on the target classpath and using source <8 or release <8 would not.

**Comment by gavra0** [comment]
They are both available even if `-source 8` is used. I think "jdk.compiler" (which contains the annotation) is part of the default bootclasspath, and JDK does not hide that annotation. Here is a repro: https://github.com/ZacSweers/CatchUp/pull/204

This fails downstream javac compilation as that one does specify `-source 8` and it does filter JDK9 version of `@Generated` annotation.

**Comment by JakeWharton** [comment]
Fixed and shipped in 0.5.2
