### ISSUE TITLE
Optionally auto generate factory interfaces?

### ISSUE THREAD

**Issue by davidliu** [square/AssistedInject#128]
Seems like it would be better to have the factory interfaces be autogenerated rather than require the boilerplate of declaring an interface (which in turn is mostly a duplicate of the constructor).

**Comment by JakeWharton** [comment]
This means that the factories would be public API which is never a good thing. I explain the motivation in this talk: https://jakewharton.com/helping-dagger-help-you/. It's a design decision not to do this, and if you want this behavior you might want to use AutoFactory instead.

**Comment by davidliu** [comment]
Sorry, I don't understand what you mean specifically by the factory being public API here (are you referring to the implementation or interface here)? Aren't the interfaces already public APIs?

Were you referring to the fact that they'd be generated and the compilation issues that accompany that (re:AutoFactory)?

**Comment by JakeWharton** [comment]
Yes, the generated factories. It violates the whole principle that Dagger, Auto, etc. preach which is that the exposed API is always hand-written and the libraries generate the implementation. This library subscribes to that philosophy, and AutoFactory, weirdly, does not (at least not by default).
