### ISSUE TITLE
Inject inline classes

### ISSUE THREAD

**Issue by kakai248** [square/AssistedInject#131]
Trying to inject inline classes I get the following error:

`error: Assisted injection requires an @AssistedInject-annotated constructor with at least one @Assisted parameter.`

It looks like that when the class is inlined by the compiler, it loses the annotation?

**Comment by JakeWharton** [comment]
If so that would be a kapt bug and should be filed against Kotlin. This is a Kotlin language feature that this processor knows nothing about nor does it have the ability to know anything about it.
