### ISSUE TITLE
how do you configure assistedinject to use with bazel

### ISSUE THREAD

**Issue by vipsy** [square/AssistedInject#135]
is bazel supported?
If so how do you configure, which class to use as `processor_class` with bazel?

**Comment by JakeWharton** [comment]
We don't explicitly support Bazel but the library is an annotation processor that will work with any build system.

The core annotation processor class is `com.squareup.inject.assisted.processor.AssistedInjectProcessor`.

The Dagger 2-specific annotation processor class is `com.squareup.inject.assisted.dagger2.processor.AssistedInjectDagger2Processor`.

The inflation injection annotation processor class is `com.squareup.inject.inflation.processor.InflationInjectProcessor`.

Each of those is bundled in its own library so you'll need to make sure the corresponding artifact is on `javac`'s `processorpath` along with any dependencies it requires.

Hope that helps. You may also want to try on StackOverflow as you can tag that question with 'bazel' and get help from people who actually use Bazel unlike me who is mostly just guessing and Googling.
