### ISSUE TITLE
Factory method parameters do not match constructor @Assisted parameters in a multi-module project

### ISSUE THREAD

**Issue by TheReprator** [square/AssistedInject#137]
Factory method parameters do not match constructor @Assisted parameters. Both parameter type and name must match.
    public UserAdminViewModal(@org.jetbrains.annotations.NotNull()
           ^
  Declared by constructor, unmatched in factory method:
   * androidx.lifecycle.SavedStateHandle savedStateHandle
  Declared by factory method, unmatched in constructor:
   * androidx.lifecycle.SavedStateHandle arg0

**Comment by JakeWharton** [comment]
Dupe of #81
