### ISSUE TITLE
`@AssistedInject_SomeClass` hides build error if the build fails

### ISSUE THREAD

**Issue by coroutineDispatcher** [square/AssistedInject#139]
Hi, 

I have encountered this issue when I have unsuccessful build unrelated to AssistedInject library.

I hit build -> Build fails. 
Then I have to delete the generated line `AssistedInject_SomeClassModule` in order to see what the real issue is. Is there a workaround for this?

I'm using version 0.5.2

**Comment by Minirogue** [comment]
I just had the same issue. Specifically, I was getting the following error 
`error: cannot find symbol
@dagger.Module(includes = {AssistedInject_AssistedInjectModule.class})`
which I believe is coming from the Dagger annotation processor as opposed to the AssistedInject processor. For the record, I verified that `AssistedInject_AssistedInjectModule.class` was, in fact, successfully generated.

Commenting out the line `@Module(includes = [AssistedInject_AssistedInjectModule::class])` in `AssistedInjectModule` (thanks @coroutineDispatcher) exposed the kapt errors coming from another annotation processor (Room in my case).

**Comment by coroutineDispatcher** [comment]
Had somehow nearly the same case but with a `Realm` object. But I think they are trying to merge `@AsistedInject` with Dagger so that you don't have 2 dependencies in your `build.gradle` for solving the same problem (factory pattern basically). If that's the case I believe this case should be closed and reported somewhere else
