### ISSUE TITLE
Support for default-generated AssistedInjector.Factory

### ISSUE THREAD

**Issue by Zhuinden** [square/AssistedInject#141]
Currently for this:

``` kotlin
class LoginViewModel @AssistedInject constructor(
    private val authenticationManager: AuthenticationManager,
    @Assisted private val savedStateHandle: SavedStateHandle
) : ViewModel() {
    class Factory @AssistedInject constructor(
        val authenticationManager: AuthenticationManager,
        @Assisted savedStateRegistryOwner: SavedStateRegistryOwner,
        @Assisted defaultArgs: Bundle
    ) : AbstractSavedStateViewModelFactory(savedStateRegistryOwner, defaultArgs) {
        @Suppress("UNCHECKED_CAST")
        override fun <T : ViewModel> create(
            key: String,
            modelClass: Class<T>,
            savedStateHandle: SavedStateHandle
        ): T = LoginViewModel(authenticationManager, savedStateHandle) as T
    }
```

I get this:

> e: F:\Work\HomeProjects\WTF\Jetpack-Navigation-MultiModule-Fragment-NavGraph-Dagger-SavedStateHandle-FTUE-Experiment\app\build\tmp\kapt3\stubs\debug\com\zhuinden\jetpacknavigationmultimodulefragmentnavgraphdaggersavedstatehandleftueexperiment\features\login\LoginViewModel.java:63: error: No nested @AssistedInject.Factory found.
>     public static final class Factory extends androidx.lifecycle.AbstractSavedStateViewModelFactory {

I was expecting to get a default `LoginViewModel_Factory_Factory.create(savedStateRegistryOwner: SavedStateRegistryOwner, defaultArgs: Bundle): LoginViewModel.Factory`, but apparently even for the simple case without something like `@BindsInstance`, `@AssistedInject.Factory` must be provided.

Is it possible to add support for default generated `@AssistedInject.Factory`?

**Comment by Zhuinden** [comment]
Maybe this problem is different than I think, I think I'll come back when I actually know what I'm talking about.

Sorry for noise.

**Comment by Zhuinden** [comment]
Okay, so the following is what works:

``` kotlin
class LoginViewModel constructor(
    private val authenticationManager: AuthenticationManager,
    private val savedStateHandle: SavedStateHandle
) : ViewModel() {
    class VmFactory @AssistedInject constructor(
        val authenticationManager: AuthenticationManager,
        @Assisted savedStateRegistryOwner: SavedStateRegistryOwner,
        @Assisted defaultArgs: Bundle
    ) : AbstractSavedStateViewModelFactory(savedStateRegistryOwner, defaultArgs) {
        @Suppress("UNCHECKED_CAST")
        override fun <T : ViewModel> create(
            key: String,
            modelClass: Class<T>,
            savedStateHandle: SavedStateHandle
        ): T = LoginViewModel(authenticationManager, savedStateHandle) as T

        @AssistedInject.Factory // https://github.com/square/AssistedInject/issues/141
        interface Factory {
            fun create(savedStateRegistryOwner: SavedStateRegistryOwner, defaultArgs: Bundle): VmFactory
        }
    }
```

1.) `LoginViewModel.Factory.Factory` confused assisted-inject so I had to make sure their names don't conflict (probably different issue)

2.) I did indeed have to add a `@AssistedInject.Factory` and I'm not sure if that shouldn't have a default, so original issue stands.

**Comment by JakeWharton** [comment]
A design principle of the library is that factories are API and thus must be explicitly defined. Consumers must not rely on generated code as public API. Libraries like AutoFactory will generate the factory for you, though.

This case seems a lot closer to inflation inject where we generate the factory and the map binding so both are implementation detail. If you want to support this case, you can write an annotation processor to generate the second-order factory which no one would ever explicitly refer to.

Or you could wait for [Hilt](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/hilt/) which handles view models. It's why we won't be adding view model support to this library.

**Comment by Zhuinden** [comment]
Apparently the magic trick was to hide the second-order factory inside a Kotlin delegate. That way, no annotation processor is needed. Thanks!
