### ISSUE TITLE
Let factory parameters be optionally injected

### ISSUE THREAD

**Issue by neworld** [square/AssistedInject#143]
#### Problem

I am creating a foundation for all fragment and ViewModel pairs according to [this](https://proandroiddev.com/connecting-the-dots-44d8fa79f14) or [this](https://proandroiddev.com/saving-ui-state-with-viewmodel-savedstate-and-dagger-f77bcaeb8b08#73d2) pattern. In order to have a uniform injection, I could use base interface for factories:
```
interface AssistedSavedStateViewModelFactory<T : ViewModel> {
    fun create(savedStateHandle: SavedStateHandle): T
}
```

To make this magic work, I am always needed to inject assisted `SavedStateHandle`, even I am not using it. Otherwise, I got an error:

> Factory method parameters do not match constructor @Assisted parameters. Both parameter type and name must match.

#### Potential solution

This case could be easily solved by marking dependencies as optional to consume:

```
    @AssistedInject.Factory
    interface Factory : AssistedSavedStateViewModelFactory<Arguments, FeatureViewModel> {
        override fun create(@OptionalToConsume savedStateHandle: SavedStateHandle): FeatureViewModel
    }
```

#### Considered alternatives

Do not use assisted inject if you do not need `SavedStateHandle`. But then you have to make tons of ugly changes if one day you need to save state. Also, [complex ViewModel factory](https://proandroiddev.com/connecting-the-dots-44d8fa79f14#c3fb) is needed.

**Comment by JakeWharton** [comment]
The AndroidX Hilt project will provide a turnkey solution for injecting view models with the saved state handle argument being optional: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/hilt/. It obviates the need to hand-write a factory yourself by generating it directly (similar to how inflation inject works in this library). As such, I don't want to add such a feature to this library unless there's a wider need for it across multiple use cases.
