### ISSUE TITLE
Only assisted arguments

### ISSUE THREAD

**Issue by SamYStudiO** [square/AssistedInject#144]
Hello
It seems my factories won't be generated if i use only @assisted arguments. Is there any reason for that?
I mean I just want my factory to be added to the graph and it has only assisted arguments, this seems legit?
Thx

**Comment by JakeWharton** [comment]
You don't really need this library for that case. You can annotate the zero-argument constructor of the factory and inject it anywhere.

That being said, I thought we added support for this but with a warning.

**Comment by SamYStudiO** [comment]
Problem is I have constructor arguments (but only assisted ones). How can i do this without using AssistedInject?

**Comment by JakeWharton** [comment]
You write a traditional factory pattern. A single method class that calls the constructor with the supplied arguments.

**Comment by SamYStudiO** [comment]
Yep that's what i was thinking but i'm lazy :D
Thx Jake!
