### ISSUE TITLE
Requesting a factory without non-Assisted parameters should not emit a warning

### ISSUE THREAD

**Issue by stoyicker** [square/AssistedInject#145]
This is a direct follow-up to #77
While I understand the solution to the part of the discussion there regarding factories for classes without @Assisted parameters, I find the other one questionable. As far as I can tell, having a factory in the other case seems like a pretty common use case if you have in mind the scenario of passing the factory via constructor so that I can mock it during testing, whereas mocking a constructor is not quite as simple (worth mention that I don't know what the `TheType::new` solution from that issue refers to so, if it solves the problem, please point out). Therefore, to me, a warning about is a 'by-default' discouragement of correct code structure.

**Comment by stoyicker** [comment]
sort of duplicates #146

**Comment by JakeWharton** [comment]
I'm still skeptical about this use case vs the other. We're not in the business of general-purpose factory generation. If you're comfortable with having to suppress the warning, though, then I'm okay with that.

**Comment by 0neel** [comment]
@stoyicker 
> worth mention that I don't know what the TheType::new solution from that issue refers to so, if it solves the problem, please point out

Here is how you can use a class constructor reference as a factory-like lambda:
```kotlin
class Something(someParam: String)

fun doThis() {
    doThat(::Something)
}

fun doThat(createSomething: (String) -> Something) {
    val something = createSomething("some param")
}
```
So you can use a lambda instead of a factory interface.
I think this what @JakeWharton is referring to.
