### ISSUE TITLE
Provide a way to suppress warnings from code

### ISSUE THREAD

**Issue by 0neel** [square/AssistedInject#146]
Is there a way to suppress the compiler warnings from code using `Suppress` annotation? 
Specifically
> Assisted injection without at least one non-@Assisted parameter doesn't need a factory

I'd like to create such a factory since I'm going to add more non-assisted parameters to the class later. This gives me a warning which I agree with but I'd like to suppress it somehow since it doesn't really help us now.

We limit the number of warnings on CI so the only way I was able to use right now is to filter the warning out by the message.

**Comment by JakeWharton** [comment]
We can add it
