### ISSUE TITLE
Kotlin data class with single field cannot have an assistedinject factory

### ISSUE THREAD

**Issue by stoyicker** [square/AssistedInject#147]
The following code block pops "error: @Assisted is only supported on constructor parameters"

```kotlin
data class Foo @AssistedInject (@Assisted val bar: Bar) {
    @AssistedInject.Factory
    interface Factory {
        fun create(bar: Bar): Foo
    }
}
```

Remove the data qualifier from the class and the factory is generated as expected.

**Comment by JakeWharton** [comment]
Can you try `@parameter:Assisted`?

**Comment by stoyicker** [comment]
`@param:@Assisted` gives the same error. `@parameter` doesn't seem to denote an annotation target

**Comment by JakeWharton** [comment]
Looks like the problem is that Kotlin copies the annotate to the `copy` method. Ugh.

**Comment by stoyicker** [comment]
I could try to put up a pull request to use kotlinx-metadata to check if the class is a data class (supposing that info is included in `@Metadata`, which I'm not sure about) and if that's the case ignore annotated parameters of methods called "copy". However it doesn't seem like a great solution

**Comment by JakeWharton** [comment]
I was going to just ignore "copy" methods without even checking metadata. Metadata is certainly the more correct solution here but I'm not sure it's strictly necessary.

**Comment by stoyicker** [comment]
Yeah I see that, the difference will probably never affect anyone. I'll just do it based on the name then. I'll try to have it in a few hours

**Comment by JakeWharton** [comment]
Thanks. I _think_ it might just be a `.filter { it.name != "copy" }` somewhere. For a test we can just write the Java equivalent of the class similar to the kapt stubs which are generated.
