### ISSUE TITLE
Carry annotations from interface into generated implementation

### ISSUE THREAD

**Issue by stoyicker** [square/AssistedInject#158]
Has this been considered? The following is an example use case:

```kotlin
class Foo @AssistedInject constructor(@Assisted val assisted: Bar) {
  @Reusable
  @AssistedInject.Factory 
  interface Factory {
    fun create(assisted: Bar): Foo
  }
}
```

to generate a factory implementation annotated with `@Reusable`:

```java
@Reusable // This line is new
public final class Foo_AssistedFactory implements Foo.Factory {
  @Inject
  public Foo_AssistedFactory() {
  }

  @Override
  public Foo create(Bar assisted) {
    return new Foo(assisted);
  }
}
```

I understand it's probably a bit questionable since something like this would also leave the interface annotated which may not be desirable, but considering interfaces have no implementation I see no major issue with it, and there may also be other mechanisms to achieve the same goal and don't have this issue. Thoughts?

**Comment by JakeWharton** [comment]
We can special case individual Dagger annotations like `@Reusable`, although I thought support for that was removed from Dagger a while ago.

**Comment by stoyicker** [comment]
[The javadoc of the latest version seems to still include it](https://javadoc.io/static/com.google.dagger/dagger/2.29.1/dagger/Reusable.html), but I don't keep up much with the latest of the Dagger community, so I don't really know.
I'll see what I can come up with for a pr and report back, thanks

**Comment by JakeWharton** [comment]
I was thinking of releasable references, not reusable.

**Comment by JakeWharton** [comment]
I would like to do a release this week. Let me know how you are progressing and if you want me to take over. We can start with just special casing that annotation.

**Comment by stoyicker** [comment]
I have a patch half-way through for annotations in dagger.* packages. Just
need to add/update some tests but I'm afk right now, I'll have it ready in
a few hours

**Comment by JakeWharton** [comment]
Ok! It's not _that_ urgent. There's three whole days left this week, and Monday would be fine, too.
