### ISSUE TITLE
InflationInject throws error when a custom view is a kotlin class with @JvmOverloads marked constructor

### ISSUE THREAD

**Issue by roshypoo** [square/AssistedInject#176]
I defined this custom class with standard @JvmOverloads annotations to it's constructor:
```
class CustomView @InflationInject @JvmOverloads constructor(
    @Inflated context: Context,
    @Inflated attrs: AttributeSet? = null,
    @Inflated defStyleAttr: Int = 0
) : FrameLayout(context, attrs, defStyleAttr)
```
But when compiling the annotation processor throws this error:
`/android/ui/custom_views/CustomView.java:11: error: Multiple @InflationInject-annotated constructors found.`

What is the proper way to do this in Kotlin? I can't find any samples, so creating an issue here. Any help is appreciated, thanks.

**Comment by JakeWharton** [comment]
You should either remove `@InflationInject` because you're not injecting any types and therefore it serves no purpose, or you can remove `@JvmOverloads` and the `defStyleAttr` attribute so that you have a single constructor that it can use.

**Comment by roshypoo** [comment]
I removed the injection type as it's just an example😅, I should have mentioned some type though. Also, some custom view might need defStyleAttr for accessing theme values though. In my case I can remove it as this view is just a container.

**Comment by JakeWharton** [comment]
`defStyleAttr` is never used when inflating from XML. If you want to allow its use for those programmatically instantiating your views then it must be a sibling constructor.

**Comment by roshypoo** [comment]
This article by Dan Lew cleared things up for me a bit regarding view constructors: https://blog.danlew.net/2016/07/19/a-deep-dive-into-android-view-constructors/. @JakeWharton I suppose we can close this issue. Thanks for the help.

**Comment by Benny6731** [comment]
> I defined this custom class with standard @JvmOverloads annotations to it's constructor:
> 
> ```
> class CustomView @InflationInject @JvmOverloads constructor(
>     @Inflated context: Context,
>     @Inflated attrs: AttributeSet? = null,
>     @Inflated defStyleAttr: Int = 0
> ) : FrameLayout(context, attrs, defStyleAttr)
> ```
> 
> But when compiling the annotation processor throws this error: `/android/ui/custom_views/CustomView.java:11: error: Multiple @InflationInject-annotated constructors found.`
> 
> What is the proper way to do this in Kotlin? I can't find any samples, so creating an issue here. Any help is appreciated, thanks.

,
