### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by jaredsburrows** [square/AssistedInject#3]
:)

**Comment by TommyLemon** [comment]
Me too. It seems that this is a Dagger2 helper library according to the name "assisted-inject-annotations-dagger2".

**Comment by JakeWharton** [comment]
No plans. It's in the open because i'm sharing it with specific people, not because you should use it.

**Comment by mishkaowner** [comment]
Will this be a similar library to [this](https://github.com/lukaspili/Auto-Dagger2)?

**Comment by Eillot** [comment]
👍

**Comment by andreasnomikos** [comment]
Do you need Assisted Injection because you want to avoid the boilerplate of another custom component for simple cases ?

**Comment by yangwuan55** [comment]
@JakeWharton My Prince Charming,can you reply to me? 😆

**Comment by jaredsburrows** [comment]
Closing since @JakeWharton said no plans.
