### ISSUE TITLE
Generated factory includes extra Provider<T> layer

### ISSUE THREAD

**Issue by btilbrook-nextfaze** [square/AssistedInject#39]
When the target class has a `Provider<T>` binding, the generated factory class includes a constructor param `Provider<Provider<T>>`. As a result, Dagger 2 can't find the binding.

Should AssistedInject flatten `Provider<T>` bindings in this case?

**Comment by JakeWharton** [comment]
Yep. Will fix.

**Comment by btilbrook-nextfaze** [comment]
Excellent, thank you.

**Comment by JakeWharton** [comment]
Released as 0.2.0 today as well.
