### ISSUE TITLE
Should this work with dagger and kotlin/kapt?

### ISSUE THREAD

**Issue by SamYStudiO** [square/AssistedInject#51]
I'm trying to make AssistedInject work with dagger and kotlin but no success so far.
It seems dagger generates module classes before assisted factories so it ends up with a error `NonExistentClass`  from the factory binding.

`@Binds
abstract fun bindHomeAssistedInjectFactory(factory: HomeAssistedInject_AssistedFactory): HomeAssistedInject.Factory`

generates :   
`@org.jetbrains.annotations.NotNull()
    @dagger.Binds()
    public abstract HomeAssistedInject.Factory bindHomeAssistedInjectFactory(@org.jetbrains.annotations.NotNull()
    NonExistentClass factory);`

I remember trying with google AutoFatory a while ago and ending up with the same pb so i guess this is a kapt problem?

Thx for help!

**Comment by JakeWharton** [comment]
Yes. You can perhaps follow Tivi's example: https://github.com/chrisbanes/tivi/commit/b7d976cec5b1a680d743da7f5bcee425acd5cc95.

Are you using a relatively modern version of Dagger and Kotlin?

**Comment by SamYStudiO** [comment]
Hum i'm was trying to add @AssistedModule on an existing non empty module, looks like we have to make that "Assisted Module"empty to make it works. So i created an empty module with @AssistedModule and include it to my existing module and now it works.

Thx Jake for the link, that helped me pointing out the pb.
