### ISSUE TITLE
AssistedModule doesnt create bindings for @AssistedInject classes in different Android module

### ISSUE THREAD

**Issue by melbystyle** [square/AssistedInject#52]
How do I make Dagger AssistedModule generate bindings for @AssistedInjected classes in different Android modules? 

When I check the generated module, I dont see any bindings for the generated factories in the other module.

**Comment by oldergod** [comment]
You need one `AssistedModule` per project module.

**Comment by melbystyle** [comment]
Holy crap. You saved my life. That makes sense.
