### ISSUE TITLE
Scoped @AssistedModule

### ISSUE THREAD

**Issue by AleksanderMielczarek** [square/AssistedInject#70]
Hello,

let's say we have objects with different scopes that are annotated using `@AssistedInject`. For now we're limited to have one `@AssistedModule` per module. In that case it force us to split scoped objects into different modules (because of missing binding error in parent component). Are there any plans to change that behavior and allow to have multiple `@AssistedModule` in one module?

**Comment by filipkowicz** [comment]
same here - currently I'm using google autofactory for that but I would be super nice to use only one "assisted injection" tool in project - and I need it scoped or at least in separate modules to use with different subcompontents. I'm injecting ViewHolders and some of dependencies are match only within certain subcomponents (handlers etc)

any plans for that?

**Comment by JakeWharton** [comment]
No immediate plans, no. The need for a module is only because this is a project separate from Dagger. Once Dagger adds first-party support for assisted injection the module requirement will disappear and scoping should work as expected.

**Comment by filipkowicz** [comment]
Thanks @JakeWharton , are you aware of any plans to include it or option to request adding assisted injection to core dagger?

**Comment by JakeWharton** [comment]
That is the plan, yes.

https://github.com/google/dagger/issues/1825
