### ISSUE TITLE
Possible solution for Arch ViewModel dynamic parameters

### ISSUE THREAD

**Issue by mtiidla** [square/AssistedInject#71]
After seeing Jake's [presentation](https://jakewharton.com/helping-dagger-help-you/) on this library at DroidCon, I was hoping that the proposed solution will solve the problem of passing dynamic parameters to Android Architecture Components ViewModel that is discussed on several places over the internet, originally probably here https://github.com/googlesamples/android-architecture-components/issues/207

Since ViewModel shouldn't be injected directly to a client as Presenter is in the examples of this library and Jake's talk, all I could come up with was double factories, the assisted factory for creating ViewModelFactory and then then ViewModelFactory to have the system lazily create the ViewModel.

Can someone see a better solution or would it require a specific fork of this library to auto generate this extra ViewModelFactory?

Ideally I would see the same solution as in Jake's presentation. No manual creation of ViewModel and no manual parameter passing, only the dynamic params to Factory create method.

My example:
**The ViewModelFactory and "ViewModelFactoryFactory"**
```
class WordDetailViewModelFactory @AssistedInject constructor(
    private val repository: WordRepository,
    @Assisted private val argument: WordDetailScreenArg
) : ViewModelProvider.Factory {

    override fun <T : ViewModel?> create(modelClass: Class<T>): T {
        return WordDetailViewModel(repository, argument) as T
    }

    @AssistedInject.Factory
    interface Factory {
        fun create(argument: WordDetailScreenArg): WordDetailViewModelFactory
    }
}
```
**The ViewModel**
```
class WordDetailViewModel(
    private val repository: WordRepository,
    argument: WordDetailScreenArg
) : ViewModel() {

    val wordDetail: LiveData<Word> = repository.word(argument.word)

    fun onDeleteWordClicked() {
        wordDetail.value?.let {
            repository.deleteWord(it.word)
        }
    }
}
```
**Injection**
```
@Inject
lateinit var viewModelFactory: WordDetailViewModelFactory.Factory;

override fun onAttach(context: Context?) {
    super.onAttach(context)

    val arguments: WordDetailScreenArg = ...
    Injection.appComponent.inject(this)

    viewModel = ViewModelProviders.of(this, viewModelFactory.create(arguments))[WordDetailViewModel::class.java]

}
```
Edit: looks like @hansenji has a solution at https://github.com/hansenji/ViewModelInject

**Comment by Ethan1983** [comment]
You might want to check @InflationInject @InflationModule which is used to avoid that another level of factories (LayoutInflator.Factory).

**Comment by eerikk** [comment]
@mtiidla have you found more elegant solution to this?

**Comment by mtiidla** [comment]
> @mtiidla have you found more elegant solution to this?

@eerikk No, unfortunately not. I have recently switched projects and am currently not using Dagger2, but Koin instead. Koin solves this exact issue as you can see [here](https://insert-koin.io/docs/1.0/documentation/reference/index.html#_viewmodel_and_injection_parameters). However, I personally care much more about Dagger2 and I am planning to look into the LayoutInflater Factory solution mentioned by Ethan1983, but haven't gotten around to it yet.

**Comment by alashow** [comment]
My solution was to have a callback on ViewModel creation in ViewModelFactory:
https://gist.github.com/alashow/67cc52c606ddc7637e75185673b7f9a6

**Comment by mtiidla** [comment]
> My solution was to have a callback on ViewModel creation in ViewModelFactory:
> https://gist.github.com/alashow/67cc52c606ddc7637e75185673b7f9a6

Thanks for proposing your solution, however it is not solving the problem. The main idea is to avoid an init method on the viewmodel and use constructor to injection arguments. Otherwise we could very well write and init method on every viewmodel and just call it (which you have just abstracted away).

**Comment by alashow** [comment]
Yeah, the reason why I abstracted it is to init the ViewModel on creation.

**Comment by evant** [comment]
I made https://github.com/evant/injectedvmprovider to try to deal with this, it lets you skip the ViewModelFactory. While we aren't currently using it with AssistedInject, we are using it with manual factories and it's working pretty well. Your example would be:

**The ViewModel**
```kotlin
class WordDetailViewModel  @AssistedInject constructor(
    private val repository: WordRepository,
    @Assisted argument: WordDetailScreenArg
) : ViewModel() {

    val wordDetail: LiveData<Word> = repository.word(argument.word)

    fun onDeleteWordClicked() {
        wordDetail.value?.let {
            repository.deleteWord(it.word)
        }
    }

    @AssistedInject.Factory
    interface Factory {
        fun create(argument: WordDetailScreenArg): WordDetailViewModel
    }
}
```

**Injection**
```kotlin
@Inject
lateinit var viewModelFactory: WordDetailViewModel.Factory;

override fun onAttach(context: Context?) {
    super.onAttach(context)

    val arguments: WordDetailScreenArg = ...
    Injection.appComponent.inject(this)

    viewModel = InjectedViewModelProviders.of(this).get(viewModelFactory, f -> f.create(arguments))
}
```

**Comment by Mayank-Bhatnagar** [comment]
Well with this approach are we not gonna end with each individual ViewModel mapped to its own ViewModelFactory. Thus, we are sacrificing the cost of loosing a generic ViewModelFactory. Please correct me if I misunderstood.

**Comment by permenko** [comment]
https://github.com/tfcporciuncula/dagger-journey

**Comment by eerikk** [comment]
We've started to use this kind of solution in our project. Dagger helps us out here 👇 
1. Generic code that lets us inject into `Fragment` and `ViewModel`. Important part here is the code inside `companion object`. We make fragment argument available for ViewModel.
```
@Module
interface ExampleModule {

    @PerFragment
    @ContributesAndroidInjector(modules = [ExampleViewModelModule::class])
    fun contributesExampleFragment(): ExampleFragment

    @Module(includes = [ViewModelFactoryModule::class])
    abstract class ExampleViewModelModule {

        @Binds
        @IntoMap
        @ViewModelKey(ExampleViewModel::class)
        abstract fun bindExampleViewModel(viewModel: ExampleViewModel): ViewModel

        @Module
        companion object {
            @Provides
            @JvmStatic
            fun providesExampleParam(fragment: ExampleFragment): String {
                return fragment.requireArguments()
                    .getString(ExampleFragment.ARG_EXAMPLE_STRING)!!
            }
        }
    }

}
```

This way we can inject the param simply to our ViewModel
```
class ExampleViewModel @Inject constructor(
    private val exampleString: String
): ViewModel{}
```
--- 
If you have multiple parameters with same type, you can use `@Named` annotation to prevent type conflicts. 👇 
```
            @Provides
            @Named(ExampleFragment.EXAMPLE_STRING)
            @JvmStatic
            fun providesExampleParam(fragment: ExampleFragment): String {
                return fragment.requireArguments()
                    .getString(ExampleFragment.ARG_EXAMPLE_STRING)!!
            }
```
...and now you can simply access it from ViewModel
```
class ExampleViewModel @Inject constructor(
    @Named(ExampleFragment.EXAMPLE_STRING) private val exampleString: String
): ViewModel{}
```

**Comment by hansenji** [comment]
This library uses Assisted Inject and SavedStateHandle to pass arguments into your viewmodel
https://github.com/hansenji/ViewModelInject.

**Comment by JakeWharton** [comment]
This functionality is going to be covered by the upcoming Hilt tool in Jetpack which integrates Dagger with view models and work manager.
