### ISSUE TITLE
Generation fails when Factory method is in base interface and uses generics

### ISSUE THREAD

**Issue by gabrielittner** [square/AssistedInject#73]
```kotlin
interface BaseThing<T> {
  interface Factory {
    fun create(view: View): BaseThing<T>
  }
}

class StringThing @AssistedInject constructor (
  @Assited view: View
): BaseThing<String> {

  @AssistedInject.Factory
  interface Factory : BaseThing.Factory<String>
}
```

This will not generate an implementation for the factory, but a generated Dagger 2 module will still try to reference the not generated factory.
Adding `override fun create(view: View): BaseThing<String>` to the Factory will fix it.

**Comment by JakeWharton** [comment]
Er, are you sure this is silent? When I wrote the test it failed with an error that the interface was empty.

**Comment by JakeWharton** [comment]
Great. I just realized I made the fix without generics so I'll have to
write another test case for that.

**Comment by JakeWharton** [comment]
Re-opening for generics. Feel free to try the SNAPSHOT in the mean time and see if it works.

**Comment by JakeWharton** [comment]
I know you have generics which is why I mentioned it. Does that mean you tried the snapshot and it doesn't work?

**Comment by gabrielittner** [comment]
Yeah I'm getting 
```
/Users/gabriel/.../SearchBinder_AssistedFactory.java:26: error: cannot find symbol
  public BaseBinder<S, E> create(View view) {
                    ^
  symbol:   class S
  location: class SearchBinder_AssistedFactory

/Users/gabriel/....w/SearchBinder_AssistedFactory.java:26: error: cannot find symbol
  public BaseBinder<S, E> create(View view) {
                       ^
  symbol:   class E
  location: class SearchBinder_AssistedFactory
```

**Comment by gabrielittner** [comment]
Works perfectly now 👍 Thanks
