### ISSUE TITLE
Why you can't have AssistedInject constructor with no non-assisted parameter?

### ISSUE THREAD

**Issue by bio007** [square/AssistedInject#77]
If I have a constructor annotated with AssistedInjection with no non-assisted parameter I get this error:

error("Assisted injection requires at least one non-@Assisted parameter.", targetConstructor)

Is this some technical limitation or it's only a rule applied.

I know it doesn't make much sense but what I'm trying to do is to establish some framework to inject ViewModels into fragments. I want the ViewModelProvider Factories (and then ViewModels) have injected by dagger. But usually there is some Assisted parameter so I'm using AssistedInjection Factories to provide that.

There can however be a VM without non-assisted parameters but I still want it to be injected the same way the others are. But with these VMs I'm getting this error.

**Comment by JakeWharton** [comment]
There's no technical limitation other than it's pointless to use it in that case and you should use `@Inject` directly instead. What is your abstraction? How can you can vary the number of parameters required? Can you just inject a `Provider<TheType>` instead?

**Comment by bio007** [comment]
Actually I can't use @Inject as there is (are) only @Assisted parameter. Dagger won't be able to create that. But I agree it's not standard use of assisted injection.

I just wanted to know if we need this check. Because if it won't break anything and it is just little odd, why to force it? :)

The factory will have zero injected parameters but it still can be a valid class.

**Comment by JakeWharton** [comment]
Ah, I see. I had it backwards. So you just want a generated factory with an empty `@Inject`-annotated constructor?

**Comment by bio007** [comment]
Yes, thats correct.

**Comment by JakeWharton** [comment]
Would it bother you if the processor emit a warning in that case? Because normally in that case you should be calling the constructor directly or using `TheType::new` as a factory.

It would be suppressable.

**Comment by bio007** [comment]
Of course not. Warning makes complete sense. Usually it is really better to just call it directly but for some cases it can be handy to have factory generated.
Thanks!

**Comment by JakeWharton** [comment]
Ok. I'll make the change. I think I'll also change the opposite case,
having zero assisted parameters, also warn instead of error.
