### ISSUE TITLE
Possibility for @FragmentInject?

### ISSUE THREAD

**Issue by alex-townsend** [square/AssistedInject#82]
The `androidx.fragment` library recently added support for supplying a custom [`FragmentFactory`](https://developer.android.com/reference/androidx/fragment/app/FragmentFactory) to handle creation (and re-creation) of Fragments. This opens a potential possibility for using Dagger to handle the creation and injection of your Fragments -- potentially supplying the arguments as `@Assisted` similarly to how `@InflationInject` is working.

Is this something you would consider adding to the library or do you think it would be better as a separate library?

**Comment by JakeWharton** [comment]
Is it needed? Fragments don't require any assisted parameters in their
constructor like views. Normal injection and multibinding should suffice.

**Comment by alex-townsend** [comment]
My use-case was for attempting to convert/refactor a project to use a Dagger-backed `FragmentFactory` for constructor injection of Fragments instead of Dagger's `AndroidInject` field-level injection, where previously some values/state was passed through the args Bundle (note: the project was not yet using Dagger, ).

Using a pattern like the `@InflationInject` with the args Bundle would allow passing in an arbitrary number of "assisted" elements through the Bundle supplied to the `FragmentFactory` when you first create the Fragment -- values could be pulled out in the init block and used however necessary in Fragment setup. I might just have missed something but I was struggling to do this in a generic/re-usable way for all Fragments using just `@AssistedInject`.

Might be more of a niche use case though, as you said there is no **required** assisted parameter in this use-case. Might be better to pull out into a separate library then?

**Comment by JakeWharton** [comment]
I don't think it requires assisted injection.

I think you want this to work like how AndroidInjection.inject(this) works
where it creates a subcomponent where the concrete type is available in a
generated subcomponent. And then if you need to access the arguments you
can either inject the subtype and call getArguments() or add a module to
the subcomponent which @Provides the Bundle by calling getArguments().

And I think we need to do this for activity, service, etc. And as a result
I think it should live in Dagger, not this library.

**Comment by alex-townsend** [comment]
Seems like that would work.

In the meantime, (fragment) constructor injecting an `@AssistedInject` factory instead of the type (i.e. Presenter.Factory instead of Presenter) and delaying calling `factory.create(...)` until the args Bundle has been set and I can pull whatever I need should work until Dagger better supports `FragmentFactory`

Looks like there is already an [issue](https://github.com/google/dagger/issues/1372) for FragmentFactory on the Dagger github as well, so I'll just close this out.

Thanks for the comments!
