### ISSUE TITLE
Error: Multiple @AssistedModule-annotated modules found

### ISSUE THREAD

**Issue by Nimrodda** [square/AssistedInject#86]
Annotating multiple modules with `@AssistedModule` results in `error: Multiple @AssistedModule-annotated modules found`. After watching your talk from [DroidCon UK '18](https://skillsmatter.com/skillscasts/11617-helping-dagger-help-you), where you mention that there should be one (and only one?) module that is annotated with `@AssistedModule` in the whole project, it all became clear to me and I managed to fix this error eventually.

At least in the current version of the library, this rule isn't mentioned (or at least unclear) in the README.md and/or the sample. Even though this behavior might change in the future, and it would be allowed to annotate multiple modules, I think it's still worth mentioning it - at least for the current behavior of the library.

**Comment by IamWinWon** [comment]
Same error.

**Comment by kakai248** [comment]
Why this limitation though? I was using `@AssistedModule` for ViewModels and now also added it for Workers. But I want to keep the waters separated. I don't want Workers references in my ViewModels module :/

**Comment by JakeWharton** [comment]
You can write individual modules by hand to avoid the restriction
