### ISSUE TITLE
Allow multiple non-assisted parameters with the same binding

### ISSUE THREAD

**Issue by btilbrook-nextfaze** [square/AssistedInject#91]
This code:

```kotlin
class MyClass @AssistedInject constructor(
    @Foo foobar1: Foobar,
    @Foo foobar2: Foobar,
    @Assisted a: String
) {
    @AssistedInject.Factory
    interface Factory {
        fun create(a: String): MyClass
    }
}
```

Produces this error:

> Duplicate non-@Assisted parameters declared. Forget a qualifier annotation?

It seems like this is an unnecessary restriction. I acknowledge that it may be an uncommon use case, but it seems reasonable that I might want to construct a `MyClass` manually in a unit test with different values for `foobar1` and `foobar2`.

In my particular case, it's 2 RxJava `Scheduler` args. When constructed via Dagger, I expect to receive the same object twice (a main thread scheduler). In my unit test, I use one of them for a timer, so I supply a `TestScheduler`, and the other for `observeOn` the main thread, so I supply `Schedulers.trampoline()`. The above error means I cannot supply the separate `Scheduler`s, which in turn means I must `triggerActions()` on my `TestScheduler` in order to execute the majority of my tests.

Can this restriction be lifted? Is it truly necessary, or a case of failing eagerly to detect programmer error?

**Comment by JakeWharton** [comment]
I agree. If you want to do this, and Dagger allows it, we shouldn't stand in the way.
