### ISSUE TITLE
Provide transitive dependencies

### ISSUE THREAD

**Issue by BraisGabin** [square/AssistedInject#94]
It would be great if AssistedInject could manage things like this:

```kotlin
class Foo @Inject constructor(activity: Activity, otherDependency: Other)

class Bar @AssistedInject constructor(foo: Foo) {

  @AssistedInject.Factory
  interface Factory {
    fun create(activity: Activity)
  }
}
```

I need to inject something but I'm missing one dependency (or more) in the graph. So I provide it using an `@AssistedInject.Factory`. The difference here is that the missing dependency is not injected directly to the class that exposes the Factory.

**Comment by JakeWharton** [comment]
I think you just want
```kotlin
class Foo @AssistedInject constructor(activity: Activity, otherDependency: Other) {
  @AssistedInject.Factory
  interface Factory {
    fun create(activity: Activity): Foo
  }
}

class Bar(foo: Foo) {
  class Factory @Inject constructor(fooFactory: Foo.Factory) {
    fun create(activity: Activity) = Bar(fooFactory.create(activity))
  }
}
```
or a subcomponent that binds the `Activity` into a small child graph allowing both `Foo` and `Bar` to be entirely constructor injected.

Doing transitive assisted injection like this in a general way means having to re-invent a lot of what Dagger is already meant to do.
