### ISSUE TITLE
Support Gradle incremental annotation processing

### ISSUE THREAD

**Issue by gildor** [square/AssistedInject#95]
AssistedInject should support Gradle incremental AP: https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing

All AP that we use in our project already supports incremental AP except AssistedInject so it's impossible to have incremental AP until all AP in your project support it

**Comment by JakeWharton** [comment]
PR welcome

**Comment by gildor** [comment]
Fixed in https://github.com/square/AssistedInject/pull/100

**Comment by matthewcmckenna** [comment]
Are there any updates on when this will be released? Very much looking forward to having this.

**Comment by JakeWharton** [comment]
Can you test it with the snapshot? Hearing that it works in the real-world would give confidence on shipping it.

**Comment by gildor** [comment]
@JakeWharton I'm using now snapshot version, everything looks fine, but it's quite tricky to test manually, probably we need some integration test for this to be sure

**Comment by matthewcmckenna** [comment]
@JakeWharton I've tested as well. I ran `./gradlew aDeb -Pkapt.verbose=true` with one dependency that I knew would fail and found that it is no longer included in the list of unsupported processors.

`[INFO] Incremental KAPT support is disabled. Processors that are not incremental: android.arch.lifecycle.LifecycleProcessor.`

**Comment by JakeWharton** [comment]
I'll do a minor release today then. Thanks for reporting in.

**Comment by JakeWharton** [comment]
Released as 0.5.0.
