### ISSUE TITLE
InflationInject doesn't provide the view.

### ISSUE THREAD

**Issue by jaychang0917** [square/AssistedInject#99]
Seems InflationInject only binds the view factory but doesn't provide the view, I ran into a use case that I need to constructor inject a view like:

```
class ProductView @InflationInject constructor(
    @Assisted context: Context,
    @Assisted attrs: AttributeSet? = null,
    imageLoader: ImageLoader
) : View(context, attrs)

class ProductListView @InflationInject constructor(
    @Assisted context: Context,
    @Assisted attrs: AttributeSet? = null,
    productViewProvider: Provider<ProductView>
) : View(context, attrs)
```

The build fails, saying "ProductView cannot be provided without an @Inject constructor or an @Provides-annotated method."

**Comment by jaychang0917** [comment]
I think there my not be a good way to allow dagger to create the view directly as view creation must be created via the inflater factory. So we may create an assisted inject factory to work around this limitation. However, there is no `@InflationInject.Factory` now, @JakeWharton do you have any idea?

**Comment by JakeWharton** [comment]
Where are the `Context` and `AttributeSet` supposed to come from in this case?

**Comment by jaychang0917** [comment]
For example, to create the `ProductView` programatically, we can pass the `Context` of `ProductListView` and no `AttributeSet` needed, am I right?

**Comment by JakeWharton** [comment]
The requested provider comes from Dagger, though. How does the context propagate to the Dagger-provided binding when it never exists in the Dagger graph?

**Comment by jaychang0917** [comment]
I don't get your meaning, for the following code, which part never exists in the Dagger graph?

```
class ProductView @InflationInject constructor(
    @Assisted context: Context,
    @Assisted attrs: AttributeSet? = null,
    imageLoader: ImageLoader
) {
    @InflationInject.Factory
    interface Factory {
        fun create(context: Context): ProductView
    }
}

class ProductListView @InflationInject constructor(
    @Assisted context: Context,
    @Assisted attrs: AttributeSet? = null,
    productViewFactory: ProductView.Factory
) {
    val productView = productViewFactory.create(context)
}
```

**Comment by JakeWharton** [comment]
Nothing. But that's a very different snippet than the original.

**Comment by jaychang0917** [comment]
> Nothing. But that's a very different snippet than the original.

Sorry for my unclear wording.🙇🏻‍♂️

**Comment by JakeWharton** [comment]
I don't think this is something that is in scope of the library. It's either that your views have normal `@Inject` constructors which means they can be injected or they're `@InflationInject` constructors which means they can be injected by the `LayoutInflater.Factory`.
